[stresstest] Fix name collisions in DEBUG_IF
- (DEBUG_IF)
Append _d_ to all variables in the macro.

Prior to this change collisions could occur, for example:

string filename = "abc";
DEBUG_IF( 1, "Filename: " << filename );

Since 'filename' is also local in DEBUG_IF it could show:

ERROR: Expression is true: 1
stresstest.cpp:190 , generate_and_compare(): Filename: stresstest.cpp